# Generated by Django 5.2.11 on 2026-02-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserID', models.CharField(max_length=100)),
                ('OrderDate', models.DateField()),
                ('ItemName', models.CharField()),
                ('OrderQty', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('TotalAmount', models.FloatField()),
                ('DeliveryAddress', models.CharField()),
            ],
        ),
    ]
